spec: create/own /etc/containers/networks
In some cases if /etc/ is mounted read-only the non-existence
of the `/etc/containers/networks` directory will cause basic
functionality to fail.

```
bash-5.2# mount --bind -o ro /etc/containers/ /etc/containers/
bash-5.2# podman info
Error: mkdir /etc/containers/networks: read-only file system
```

Since it's going to get created anyway let's just have the
directory exist from the beginning.

Signed-off-by: Dusty Mabe <dusty@dustymabe.com>
(cherry picked from commit 9f2002baed0b72bf931a22ae169aa8f806313a5d)